# Generated by Django 3.1.6 on 2021-03-28 19:17

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('street', models.CharField(max_length=256)),
                ('street_number', models.CharField(blank=True, default=True, max_length=16)),
                ('zip', models.CharField(max_length=24)),
                ('city', models.CharField(max_length=64)),
                ('country', models.CharField(blank=True, default='', max_length=64)),
                ('key', models.CharField(blank=True, max_length=128, null=True)),
                ('location_name', models.CharField(blank=True, max_length=128, null=True)),
                ('location_ID', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_EN', models.CharField(default='', max_length=128)),
                ('name_DE', models.CharField(default='', max_length=128)),
                ('description_EN', models.TextField(null=True)),
                ('description_DE', models.TextField(null=True)),
                ('discipline_EN', models.CharField(max_length=64, null=True)),
                ('discipline_DE', models.CharField(max_length=64, null=True)),
                ('network_manager', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=24)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(null=True)),
                ('assigned_to', models.CharField(max_length=24)),
            ],
            options={
                'unique_together': {('lang', 'name', 'assigned_to')},
            },
        ),
        migrations.CreateModel(
            name='CustomerPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=64)),
                ('rights', models.CharField(choices=[('all', 'View all content'), ('admin', 'Create/edit/delete all content'), ('creator', 'Create/edit/delete owned content'), ('none', 'None')], max_length=24)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='account.customergroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=128, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128, null=True)),
                ('phone', models.CharField(blank=True, max_length=24, null=True)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(max_length=128, null=True)),
                ('avatar', models.ImageField(null=True, upload_to='user-avatars')),
                ('lang', models.CharField(default='en-GB', max_length=16, null=True)),
                ('payment_account', models.CharField(max_length=128, null=True)),
                ('is_confirmed', models.BooleanField(default=False, null=True)),
                ('street', models.CharField(max_length=256)),
                ('street_number', models.CharField(blank=True, default=True, max_length=16)),
                ('zip', models.CharField(max_length=24)),
                ('city', models.CharField(max_length=64)),
                ('country', models.CharField(blank=True, default='', max_length=64)),
                ('tenant_id', models.IntegerField()),
                ('groups', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.customergroup')),
                ('user_permissions', models.ManyToManyField(blank=True, to='account.CustomerPermission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
