# Generated by Django 3.1.6 on 2021-03-28 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=64)),
                ('location_name', models.CharField(max_length=128)),
                ('location_ID', models.CharField(max_length=64)),
                ('translations', models.ManyToManyField(related_name='warehouses', to='account.Translation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WarehouseStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('unit_id', models.CharField(max_length=128, unique=True)),
                ('translations', models.ManyToManyField(related_name='units', to='account.Translation')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='warehouse.warehouse')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
