# Generated by Django 3.1.6 on 2021-03-28 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, default='uidSettings', max_length=64, null=True)),
                ('expenses', models.JSONField(blank=True, null=True)),
                ('help_desk_tickets', models.JSONField(blank=True, null=True)),
                ('inventory', models.JSONField(blank=True, null=True)),
                ('payments', models.JSONField(blank=True, null=True)),
                ('purchase_order', models.JSONField(blank=True, null=True)),
                ('sales_order', models.JSONField(blank=True, null=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='SMTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(blank=True, max_length=32, null=True)),
                ('port', models.CharField(blank=True, max_length=16, null=True)),
                ('sender_name', models.CharField(blank=True, max_length=128, null=True)),
                ('user', models.CharField(blank=True, max_length=128, null=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ShopStyling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='shop')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='shop')),
                ('skin_type', models.CharField(blank=True, max_length=24, null=True)),
                ('type', models.CharField(blank=True, max_length=128, null=True)),
                ('lazy_load', models.BooleanField(default=False)),
                ('preloades', models.BooleanField(default=False)),
                ('custom_css', models.CharField(blank=True, max_length=64, null=True)),
                ('color1', models.CharField(blank=True, max_length=8, null=True)),
                ('color2', models.CharField(blank=True, max_length=8, null=True)),
                ('color3', models.CharField(blank=True, max_length=8, null=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ImageSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_width', models.IntegerField()),
                ('preview_width', models.IntegerField()),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='HeaderSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, default='headerSettings', max_length=64, null=True)),
                ('layout', models.CharField(blank=True, max_length=64, null=True)),
                ('elements', models.JSONField(blank=True, null=True)),
                ('is_sticky', models.BooleanField(blank=True, default=False)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('street', models.CharField(blank=True, max_length=128, null=True)),
                ('zip', models.CharField(blank=True, max_length=24, null=True)),
                ('city', models.CharField(blank=True, max_length=64, null=True)),
                ('country', models.CharField(blank=True, max_length=64, null=True)),
                ('court', models.CharField(blank=True, max_length=128, null=True)),
                ('ceo', models.CharField(blank=True, max_length=128, null=True)),
                ('tax', models.CharField(blank=True, max_length=64, null=True)),
                ('vat', models.CharField(blank=True, max_length=64, null=True)),
                ('bank', models.CharField(blank=True, max_length=64, null=True)),
                ('owner', models.CharField(blank=True, max_length=64, null=True)),
                ('iban', models.CharField(blank=True, max_length=64, null=True)),
                ('bic', models.CharField(blank=True, max_length=64, null=True)),
                ('slogan', models.CharField(blank=True, max_length=64, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logo')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=24)),
                ('breadcrumbs_on', models.BooleanField(default=False)),
                ('locale', models.CharField(blank=True, max_length=128, null=True)),
                ('shop_hotline', models.CharField(blank=True, max_length=128, null=True)),
                ('shop_tagline', models.CharField(blank=True, max_length=128, null=True)),
                ('shop_title', models.CharField(blank=True, max_length=128, null=True)),
                ('shop_url', models.CharField(blank=True, max_length=128, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'unique_together': {('tenant_id', 'lang')},
            },
        ),
        migrations.CreateModel(
            name='ShopNewsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=24)),
                ('type', models.CharField(blank=True, max_length=128, null=True)),
                ('target_url', models.CharField(blank=True, max_length=128, null=True)),
                ('popup_text', models.CharField(blank=True, max_length=256, null=True)),
                ('button_text', models.CharField(blank=True, max_length=256, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('popup_image', models.ImageField(blank=True, null=True, upload_to='shop')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'unique_together': {('tenant_id', 'lang')},
            },
        ),
        migrations.CreateModel(
            name='SalesOrderSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=24)),
                ('collections', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('header', models.CharField(blank=True, max_length=128, null=True)),
                ('header_bottom', models.CharField(blank=True, max_length=128, null=True)),
                ('type', models.CharField(blank=True, max_length=64, null=True)),
                ('template_name', models.CharField(blank=True, max_length=128, null=True)),
                ('template_signature', models.CharField(blank=True, max_length=128, null=True)),
                ('template_suffix', models.CharField(blank=True, max_length=64, null=True)),
                ('template_text', models.TextField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'unique_together': {('tenant_id', 'lang')},
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=24)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'unique_together': {('tenant_id', 'lang')},
            },
        ),
    ]
