# Generated by Django 3.1.6 on 2021-03-28 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(null=True)),
                ('account_number', models.CharField(max_length=128, null=True)),
                ('account_type', models.CharField(max_length=64, null=True)),
                ('split_profit', models.BooleanField(default=False, null=True)),
                ('account_cost', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('account_profit', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('default_for', models.CharField(max_length=64, null=True)),
                ('translations', models.ManyToManyField(null=True, related_name='accounts', to='account.Translation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(null=True)),
                ('number', models.CharField(max_length=128)),
                ('account_type', models.CharField(max_length=128)),
                ('online', models.BooleanField(default=False, null=True)),
                ('opening_date', models.DateField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_accounts', to='payment.account')),
                ('translations', models.ManyToManyField(null=True, related_name='payment_accounts', to='account.Translation')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiver_account', models.CharField(max_length=128)),
                ('status', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=24)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('note', models.CharField(max_length=128)),
                ('marketplace_id', models.CharField(blank=True, max_length=128, null=True)),
                ('bookkeeping_status', models.CharField(blank=True, max_length=64, null=True)),
                ('is_locked', models.BooleanField(blank=True, default=True, null=True)),
                ('in_trash', models.BooleanField(default=False, null=True)),
                ('user_owner', models.CharField(max_length=128)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='payment.paymentaccount')),
                ('translations', models.ManyToManyField(null=True, related_name='payments', to='account.Translation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
