# Generated by Django 3.1.6 on 2021-03-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(blank=True, max_length=64, null=True)),
                ('password', models.CharField(blank=True, max_length=64, null=True)),
                ('signature', models.CharField(blank=True, max_length=128, null=True)),
                ('type', models.CharField(max_length=24, unique=True)),
                ('acc_number', models.CharField(blank=True, max_length=64, null=True)),
                ('user', models.CharField(blank=True, max_length=64, null=True)),
                ('user_password', models.CharField(blank=True, max_length=64, null=True)),
                ('username', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('locale', models.CharField(max_length=12, unique=True)),
                ('name', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_title', models.CharField(max_length=128)),
                ('tax_description', models.TextField(null=True)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=0, max_digits=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=12)),
                ('template', models.CharField(choices=[('reset_password', 'Reset your password'), ('account_created', 'Confirm your account'), ('invitation', 'Invitation to try our app'), ('collaboration', 'Invitation to collaborate under project'), ('purchase_invoice', 'Purchase invoice for order')], max_length=64)),
                ('html', models.TextField()),
            ],
            options={
                'unique_together': {('lang', 'template')},
            },
        ),
        migrations.CreateModel(
            name='CustomPages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=12)),
                ('page_category', models.CharField(max_length=128, null=True)),
                ('page_inner', models.TextField(null=True)),
                ('page_name', models.CharField(max_length=64)),
                ('page_title', models.CharField(max_length=254, null=True)),
            ],
            options={
                'unique_together': {('lang', 'page_name')},
            },
        ),
        migrations.CreateModel(
            name='CustomElements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=12)),
                ('element_content', models.TextField(null=True)),
                ('element_location', models.CharField(max_length=128)),
                ('element_title', models.CharField(max_length=128, null=True)),
            ],
            options={
                'unique_together': {('lang', 'element_location')},
            },
        ),
    ]
