# Generated by Django 3.2 on 2021-04-10 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdata',
            old_name='TSD_age_warning',
            new_name='tsd_age_warning',
        ),
        migrations.RenameField(
            model_name='productdata',
            old_name='TSD_language',
            new_name='tsd_language',
        ),
        migrations.RenameField(
            model_name='productdata',
            old_name='TSD_warning',
            new_name='tsd_warning',
        ),
    ]
