# Generated by Django 3.1.6 on 2021-03-30 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superuser',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
